### ISSUE TITLE
Angle Issue

### ISSUE THREAD

**Issue by Critlium** [2Friendly4You/PointerDiagram#1]
The Angle i put in isn't working right. ( i think )

I convert 90 degrees in radians:
90 => 1.570796

Then i put it in the text file: 
[{"type":"Pointer","data":{"x":0,"y":0,"length":140,"angle":1.570796,"color":"blue","lineWidth":1,"id":21601}}]

It should then convert back to degree:
  // convert from radians to degrees
  angle = angle * (180 / Math.PI);
  
But the Output isn't 90 degrees
![New Document(1)(2)](https://github.com/2Friendly4You/PointerDiagram/assets/128078867/1b43aba8-9848-4f3d-a20c-f63dc9a297ad)

I am not understanding something?

**Comment by 2Friendly4You** [comment]
The function I used to draw the arrow used Math.cos, which uses radians and not degrees, which means that all arrows were drawn incorrectly. Now the text files and background processing use degrees as the default. The arrows start on the right and then move to the left as the angle increases positively.

PS: The whole project is not really active at the moment, but this will change soon (in 3 weeks). Then I will develop a user interface to add the pointers and texts so that you can use the programme in a meaningful way.
